Ensure ec2.py has the required modules
Adding `six==1.9.0` to the requirements.txt file to prevent the
following error:

```
ERROR: Inventory script (ec2.py) had an execution error: Traceback (most
recent call last):
  File "/Users/martin/code/multicloud-deploy/ec2.py", line 125, in
<module>
    import six
ImportError: No module named six
```